console.log($('div').attr('hello'))
console.log($('div').attr('id'))
$('div').attr('a',100)
$('div').attr('id','container')
$('div').removeAttr('a')
$('div').removeAttr('id')
$('div').prop('id','container')
$('div').prop('a','100')
console.log($('div'))
console.log($('div').prop('id'))
console.log($('div').prop('hello'))
console.log($('div').prop('a'))
// $('div').removeProp('a')